export const projectsData = [
  {
    id: 1,
    title: "IES | 2022",
    description: "Web  | IES TECH SOLUTIONS",
    image:
      "https://i.postimg.cc/Rh6H5FwV/Captura-desde-2023-06-06-16-32-53.png",
    techStack: ["HTML", "CSS"],
    demoLink: "https://iestechsolutions.com/",
    sourceLink:
      "https://github.com/rodrigoc89/ProyectoFinal-JavaScript-RodrigoCastellanos.git",
  },
  {
    id: 2,
    title: "Ecommerce | 2022",
    description: "Proyecto  Ecommerce | CODERHOUSE",
    image: "https://i.postimg.cc/nzBRtLGS/ecommerce-javascript.png",
    techStack: ["HTML5", "CSS", "JavaScript"],
    demoLink: "https://ecommercejavascript.vercel.app/",
    sourceLink:
      "https://github.com/rodrigoc89/ProyectoFinal-JavaScript-RodrigoCastellanos.git",
  },
  {
    id: 3,
    title: "XGAMES | 2022",
    description: "Proyecto Ecommerce | CODERHOUSE",
    image: "https://i.postimg.cc/5N53kqDC/Xgames.png",
    techStack: ["HTML5", "CSS", "JavaScript", "React"],
    demoLink: "https://xgames-eight.vercel.app/",
    sourceLink: "https://github.com/rodrigoc89/xgames-RodrigoCastellanos.git",
  },
  {
    id: 4,
    title: "House Of Dev | 2023",
    description: "Proyecto integrador Bootcamp P5",
    techStack: [
      "Nodejs",
      "Postgresql",
      "Express",
      "Sequelize",
      "JWT",
      "javascript",
      "React",
      "Redux",
      "Axios",
      "React Bootstrap",
    ],
    image:
      "https://i.postimg.cc/fLXB3ydK/Captura-desde-2023-04-13-17-59-22.png",
    demoLink: "https://house-of-dev.vercel.app/",
    sourceLink: "https://github.com/cristian-23/House-of-Dev.git",
  },
  {
    id: 4,
    title: "LIFTWAY | 2023",
    description: "Aplicación mobile en desarrollo",
    techStack: [
      "Nodejs",
      "Postgresql",
      "Express",
      "Sequelize",
      "JWT",
      "javascript",
      "React Native",
      "Expo",
      "Redux",
      "Axios",
      "css",
    ],
    image: "https://i.postimg.cc/ZRHh1pd5/Fitway.png",
    // demoLink: "",
    // sourceLink: "",
  },
  {
    id: 5,
    title: "Sistema de gestion de expedientes | 2023",
    description:
      "Desarrollo frontend del sistema de expedientes de la Municipalidad de Monte Quemado",
    techStack: ["javascript", "React", "Redux", "Bootstrap", "Axios", "JWT"],
    image:
      "https://i.postimg.cc/9MVGVRVg/Captura-desde-2023-12-21-15-12-56.png",
    // demoLink: "",
    // sourceLink: "",
  },
];
